


# ==========================
#
# CONSTS
#
MENU_CHOICE_INVALID = -1
MENU_CHOICE_EXIT = 99
MENU_CHOICE_LATEST = 1
MENU_CHOICE_ADDRESS = 2
MENU_CHOICE_ACCOUNT_BALANCE = 3
MENU_CHOICE_CREATE_TRANSACTION = 10
LIST_MENU_CHOICES = [
    ("View latest block", MENU_CHOICE_LATEST),
    ("Search by address", MENU_CHOICE_ADDRESS),
    ("View account balance", MENU_CHOICE_ACCOUNT_BALANCE),
    ("Create transaction", MENU_CHOICE_CREATE_TRANSACTION),
    ("Exit", MENU_CHOICE_EXIT),
]
