


# ==========================
#
# CONSTS
#
MENU_CHOICE_INVALID = -1
MENU_CHOICE_EXIT = 99
MENU_CHOICE_LATEST = 1
MENU_CHOICE_ADDRESS = 2
MENU_CHOICE_USERNAME = 3
LIST_MENU_CHOICES = [
    ("Latest", MENU_CHOICE_LATEST),
    ("By Address", MENU_CHOICE_ADDRESS),
    ("By Username", MENU_CHOICE_USERNAME),
    ("Exit", MENU_CHOICE_EXIT),
]
